// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigurationReader is an autogenerated mock type for the ConfigurationReader type
type ConfigurationReader struct {
	mock.Mock
}

// LoadConfiguration provides a mock function with given fields: configPath
func (_m *ConfigurationReader) LoadConfiguration(configPath string) error {
	ret := _m.Called(configPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(configPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigurationReader creates a new instance of ConfigurationReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationReader {
	mock := &ConfigurationReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
