// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SqlMigrator is an autogenerated mock type for the SqlMigrator type
type SqlMigrator struct {
	mock.Mock
}

// Migration provides a mock function with given fields:
func (_m *SqlMigrator) Migration() {
	_m.Called()
}

// Seeding provides a mock function with given fields: scriptDir
func (_m *SqlMigrator) Seeding(scriptDir string) {
	_m.Called(scriptDir)
}

// NewSqlMigrator creates a new instance of SqlMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqlMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *SqlMigrator {
	mock := &SqlMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
